### PR TITLE
fix topi c++ conv2d_nchw lambda expr issue

### LINKED ISSUE #3562: [TOPI][C++]conv2d_nchw mistake?
Hi,
    file: topi/include/topi/nn.h
    conv2d_nchw()
    `T(b, i, stride_h * h + kh, stride_w * w + kw) * W(i, o, kh, kw)`
    I think `W(i, o, kh, kw)` should be `W(o, i, kh, kw)`, am I right?
    
@ashokei

### PR DESCRIPTION
**Pull request by zacario-li**
weight tensor's usage should be `W(o, i, kh, kw)`
fix #3562

### CODE REVIEW

File: topi/include/topi/nn.h [hunk 1]
```diff
@@ -268,7 +268,7 @@ inline tvm::Tensor conv2d_nchw(const tvm::Tensor& I,
                : pad(I, {tvm::Expr(0), tvm::Expr(0), pad_h, pad_w});
   auto l = [&](tvm::Var b, tvm::Var o, tvm::Var h, tvm::Var w) {
     return tvm::sum(
-        T(b, i, stride_h * h + kh, stride_w * w + kw) * W(i, o, kh, kw),
+        T(b, i, stride_h * h + kh, stride_w * w + kw) * W(o, i, kh, kw),
```
Comment (kevinthesun) [inline topi/include/topi/nn.h]: Do we have any test case for conv2d cpp implementation?

Comment (zacario-li) [reply topi/include/topi/nn.h]: Sorry, no test conv2d cpp implementation there.
